name: workshop
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.9
 - pip
 - git
 - pylint
 
 # JupyterLab
 #------------
 - jupyter
 - jupyterlab
 - nodejs
 #- jupyterlab-git
 #- jupyter-lsp
 #- jupyter-lsp-python
    # Also manually installed these:
    #  jupyter labextension install @jupyterlab/toc
    #  jupyter labextension install @jupyterlab/shortcutui
    #  jupyter labextension install @krassowski/jupyterlab-lsp
    #  jupyter labextension install @ijmbarr/jupyterlab_spellchecker   
 
 # Toolbox
 #---------
 - requests
 - matplotlib
 - cartopy
 - numpy
 - scipy
 - scikit-learn
 - pandas
 - xarray
 - rasterio
 - imageio
 - netcdf4
 - eccodes
 - cfgrib
 - pygrib
 - h5py
 - h5netcdf
 #- xesmf      # Not available on PC (v0.5.0 only works with xarray 0.16.0, but that has issues)
 #- esmpy      # Not available on PC
 - metpy
 
 #- alphashape  # needed for concave hulls

 # Access to Amazon AWS S3 and other cloud storage
 - s3fs

 # Access to Unidata Catalog and THREDDS Data Servers
 - siphon

 # For Sphinx Documentation
 - sphinx
 - nbsphinx
 - sphinx_rtd_theme          # ReadTheDocs Sphinx Theme (Lots of others)
 - pydata-sphinx-theme       # PyData Sphinx Theme (i.e, Numpy, Pandas, MetPy)
 - recommonmark
 - sphinxcontrib-jsmath
 - sphinx-markdown-tables
 - autodocsumm
 - latexmk

 # Other
 #-------
 - pip:
   - highlight-text
   #- git+https://github.com/blaylockbk/HRRR_archive_download
   #- git+https://github.com/blaylockbk/SynopticPy
   #- git+https://github.com/blaylockbk/goes2go
   #- git+https://github.com/blaylockbk/Carptenter_Workshop
